FROM node:18.3.0-alpine3.14

RUN apk add --no-cache bash

WORKDIR /base

RUN chmod -R 755 ./

COPY ./tsconfig.json ./

WORKDIR /base

COPY ./package.json ./

RUN npm install --unsafe-perm --legacy-peer-deps

COPY ./ ./

EXPOSE 3000

CMD [ "npm", "run", "start" ]