version: '3.8'

volumes:
  postgres-data:

services:
  postgres:
    image: 'postgres:13'
    container_name: postgres
    restart: on-failure
    volumes:
      - postgres-data:/data
    env_file:
      - .env.${ENV}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  back-end:
    build:
      context: .
      dockerfile: docker/development/dockerfile
    container_name: back-end
    restart: on-failure
    env_file:
      - .env.${ENV}
    volumes:
      - /base/node_modules/
      - ./:/base
    depends_on:
      - postgres
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    command: bash -c "npm i && npm run test && npm run start:dev"