export enum PokemonType {
  FLYING = 'flying',
  DRAGON = 'dragon',
  GHOST = 'ghost',
  NORMAL = 'normal',
  POISON = 'poison',
  GRASS = 'grass',
  PSYCHIC = 'psychic',
  FIGHTING = 'fighting',
  ELECTRIC = 'electric',
  ICE = 'ice',
  FIRE = 'fire',
  DARK = 'dark',
  STEEL = 'steel',
  BUG = 'bug',
  GROUND = 'ground',
  ROCK = 'rock',
  WATER = 'water',
  FAIRY = 'fairy',
}
